USE screenAlert_system;

DROP TABLE IF EXISTS userContas;

CREATE TABLE userContas (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    senha VARCHAR(255) NOT NULL,
    dataCriacao DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);